"""remove mobile from clients

Revision ID: 4dd0ce4437b3
Revises: 9e8f1c598dbc
Create Date: 2025-11-30 19:53:48.346389
"""
from alembic import op
import sqlalchemy as sa


# --- Revision identifiers (required by Alembic) ---
revision = '4dd0ce4437b3'
down_revision = '9e8f1c598dbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
