"""timestamps onupdate

Revision ID: 9e8f1c598dbc
Revises: b4885a95d0d3
Create Date: 2025-11-12 19:59:21.427940
"""
from alembic import op
import sqlalchemy as sa


# --- Revision identifiers (required by Alembic) ---
revision = '9e8f1c598dbc'
down_revision = 'b4885a95d0d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
