"""sync models fields & nullability

Revision ID: b4885a95d0d3
Revises: 5124fcc960ad
Create Date: 2025-11-12 18:13:16.666298
"""
from alembic import op
import sqlalchemy as sa


# --- Revision identifiers (required by Alembic) ---
revision = 'b4885a95d0d3'
down_revision = '5124fcc960ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('amount_due',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('amount_due',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###
